# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: yarn install
        id: install
        run: yarn install
      - name: yarn lint
        id: lint
        run: yarn lint
      - name: The job has failed
        if: ${{ failure() }}
        uses: MrOggy85/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: build ${{ github.repository }} has ${{ job.status }}
          content_type: text/html
          convert_markdown: true
          body: |
            # Status: ${{ job.status }}
            Link to [Build](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
            
            ## Steps
            * Yarn Install: **${{steps.install.outcome}}**
            * Yarn Lint: **${{steps.lint.outcome}}**
    
            ## Info
            * Repo: *${{ github.repository }}*
            * Worflow: *${{ github.workflow }}*
            * Branch: *${{ github.ref }}*
            * Event: *${{ github.event_name }}*
          to: github@ringuren.com
          from: Github Action
